import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { SectionCard } from "@/components/dashboard/SectionCard";
import { useAuth } from "@/auth/AuthProvider";
import { supabase } from "@/integrations/supabase/client";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { useWorkspaceRole } from "@/hooks/useWorkspaceRole";
import { toast } from "@/hooks/use-toast";
import { useI18n } from "@/i18n/I18nProvider";
import type { ReactNode } from "react";
import type { Lang, TranslationKey } from "@/i18n/translations";

type Row = Record<string, string | number | boolean | null>;
type OptionalViewData = { rows: Row[]; unavailableReason: string | null };
type AlertsData = { telegramChats: OptionalViewData; telegramRoutes: OptionalViewData; outboxPending: OptionalViewData; actionRequestsPending: OptionalViewData; telegramHitlHealth: OptionalViewData; telegramHitlProductionHealth: OptionalViewData; operationalAlertsRecent: OptionalViewData; operationalAlertsHealth: OptionalViewData };
type Translate = (key: TranslationKey) => string;

const WORKSPACE_ID = "5ebbe435-fd79-44c3-834e-642e8fba00dc";
const DISPATCH_MAX_MESSAGES = 10;
const PLACEHOLDER_PATTERNS = ["test agency", "test client", "northstar digital clinic", "evergreen growth program", "main webinar funnel", "placeholder", "demo", "mock", "test_upload", "backend_test"];
const EVENT_LABEL_KEYS: Record<string, TranslationKey> = { stale_import_alert: "alertsEventStaleImport", ads_sync_failure_alert: "alertsEventAdsSyncFailure", source_failure_alert: "alertsEventSourceFailure", import_failure_alert: "alertsEventImportFailure", telegram_dispatch_failure_alert: "alertsEventTelegramDispatchFailure", backup_failure_alert: "alertsEventBackupFailure", restore_failure_alert: "alertsEventRestoreFailure", mapping_review_alert: "alertsEventMappingReview", manual_alert: "alertsEventManual" };
const VALUE_LABEL_KEYS: Record<string, TranslationKey> = { active: "alertsValueActive", group: "alertsValueGroup", resolved: "alertsValueResolved", open: "alertsValueOpen", warning: "alertsValueWarning", error: "alertsValueError", critical: "alertsValueCritical", healthy: "alertsValueHealthy", queued: "alertsValueQueued", failed: "alertsValueFailed", sent: "alertsValueSent", pending: "alertsValuePending", true: "alertsValueEnabled", false: "alertsValueDisabled" };
const COLUMN_LABEL_KEYS: Record<string, TranslationKey> = { chat_title: "alertsThChatTitle", chat_name: "alertsThChatTitle", title: "alertsThTitle", name: "alertsThTitle", chat_type: "alertsThType", type: "alertsThType", status: "alertsThStatus", created_at: "alertsThCreated", updated_at: "alertsThUpdated", route_name: "alertsThRoute", route_type: "alertsThRoute", route: "alertsThRoute", event_type: "alertsThEventType", severity: "alertsThSeverity", resolved_at: "alertsThResolved", message_type: "alertsThMessageType", destination_chat: "alertsThDestination", action_type: "alertsThAction", requested_by: "alertsThRequestedBy", requested_by_user: "alertsThRequestedBy", related_object: "alertsThRelatedObject", object_type: "alertsThObjectType", active_chats: "alertsTechnicalActiveChats", active_routes: "alertsTechnicalActiveRoutes", queued_messages: "alertsTechnicalQueuedMessages", failed_messages_last_24h: "alertsTechnicalFailedMessages24h", pending_action_requests: "alertsTechnicalPendingActionRequests", open_alerts: "alertsTechnicalOpenAlerts", alerts_last_24h: "alertsTechnicalAlerts24h" };

export default function Alerts() {
  const { session } = useAuth();
  const { t, lang } = useI18n();
  const queryClient = useQueryClient();
  const { capabilities, isLoading: roleLoading, error: roleError } = useWorkspaceRole(WORKSPACE_ID);
  const canManage = capabilities.can_manage_telegram_alerts;
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [technicalDetails, setTechnicalDetails] = useState<string>("");
  const [pendingAction, setPendingAction] = useState<string>("");
  const [selectedActionRequest, setSelectedActionRequest] = useState<Row | null>(null);

  const query = useQuery<AlertsData>({ queryKey: ["telegram-alerts-workspace", WORKSPACE_ID], enabled: Boolean(session), queryFn: async () => {
    const [telegramChats, telegramRoutes, outboxPending, actionRequestsPending, telegramHitlHealth, telegramHitlProductionHealth, operationalAlertsRecent, operationalAlertsHealth] = await Promise.all([readOptionalView("v_telegram_chats"), readOptionalView("v_telegram_notification_routes"), readOptionalView("v_telegram_outbox_pending"), readOptionalView("v_telegram_action_requests_pending"), readOptionalView("v_telegram_hitl_health"), readOptionalView("v_telegram_hitl_production_health"), readOptionalView("v_operational_alerts_recent"), readOptionalView("v_operational_alerts_health")]);
    return { telegramChats, telegramRoutes, outboxPending, actionRequestsPending, telegramHitlHealth, telegramHitlProductionHealth, operationalAlertsRecent, operationalAlertsHealth };
  }});

  const chats = useMemo(() => filterRows(query.data?.telegramChats.rows ?? []), [query.data?.telegramChats.rows]);
  const routes = useMemo(() => filterRows(query.data?.telegramRoutes.rows ?? []), [query.data?.telegramRoutes.rows]);
  const outbox = useMemo(() => filterRows(query.data?.outboxPending.rows ?? []), [query.data?.outboxPending.rows]);
  const requests = useMemo(() => filterRows(query.data?.actionRequestsPending.rows ?? []), [query.data?.actionRequestsPending.rows]);
  const alerts = useMemo(() => filterRows(query.data?.operationalAlertsRecent.rows ?? []), [query.data?.operationalAlertsRecent.rows]);
  const openAlerts = useMemo(() => alerts.filter((row) => !isResolvedAlert(row)), [alerts]);
  const resolvedAlerts = useMemo(() => alerts.filter(isResolvedAlert), [alerts]);
  const queuedOutboxRows = outbox.filter((row) => isOutboxStatus(row, "queued"));
  const failedOutboxRows = outbox.filter((row) => isOutboxStatus(row, "failed"));
  const firstActionRequest = requests[0];
  const firstOpenAlert = openAlerts[0];

  const refreshAlerts = async () => { await query.refetch(); await Promise.all([queryClient.invalidateQueries({ queryKey: ["telegram-alerts-workspace", WORKSPACE_ID] }), queryClient.invalidateQueries({ queryKey: ["v_telegram_outbox_pending", WORKSPACE_ID] }), queryClient.invalidateQueries({ queryKey: ["v_telegram_action_requests_pending", WORKSPACE_ID] }), queryClient.invalidateQueries({ queryKey: ["v_operational_alerts_recent", WORKSPACE_ID] }), queryClient.invalidateQueries({ queryKey: ["v_operational_alerts_health", WORKSPACE_ID] }), queryClient.invalidateQueries({ queryKey: ["v_telegram_hitl_health", WORKSPACE_ID] }), queryClient.invalidateQueries({ queryKey: ["v_telegram_hitl_production_health", WORKSPACE_ID] })]); };
  const fail = (details: string) => { setStatusMessage(t("alertsActionFailedDescription")); setTechnicalDetails(details); toast({ title: t("alertsActionFailedTitle"), description: t("alertsActionFailedDescription"), variant: "destructive" }); };
  const runAction = async (key: string, fn: () => Promise<{ data: unknown; error: { message: string } | null }>) => { setPendingAction(key); setStatusMessage(""); setTechnicalDetails(""); const { data, error } = await fn(); setPendingAction(""); if (error) return fail(error.message); const result = data as { ok?: boolean; error?: string } | null; if (!result?.ok) return fail(result?.error ?? "Action failed"); setStatusMessage(t("alertsActionDone")); toast({ title: t("alertsDoneTitle"), description: t("alertsActionDone") }); await refreshAlerts(); };
  const runDispatchQueue = async () => { if (!session?.access_token) return fail("Missing active user session."); setPendingAction("dispatch-outbox"); setStatusMessage(""); setTechnicalDetails(""); try { const { data, error } = await supabase.functions.invoke("telegram-dispatch", { body: { workspace_id: WORKSPACE_ID, max_messages: DISPATCH_MAX_MESSAGES }, headers: { Authorization: `Bearer ${session.access_token}` } }); if (error) return fail(await getFunctionErrorMessage(error)); const message = formatDispatchResult(data as DispatchResult | null, t); setStatusMessage(message); toast({ title: t("alertsQueueProcessed"), description: message }); await refreshAlerts(); } catch (error) { fail(error instanceof Error ? error.message : String(error)); } finally { setPendingAction(""); } };

  return <DashboardLayout title={t("alertsPageTitle")} subtitle={t("alertsPageSubtitle")}>
    <p className="mb-2 text-xs text-muted-foreground">{t("alertsPageHelper")}</p>{statusMessage ? <p className="mb-4 text-xs text-muted-foreground">{statusMessage}</p> : null}{technicalDetails ? <TechnicalDetails title={t("alertsTechnicalDetails")}><pre className="whitespace-pre-wrap">{technicalDetails}</pre></TechnicalDetails> : null}{!roleLoading && !canManage ? <p className="mb-4 text-xs text-muted-foreground">{t("alertsNoManageAccess")}</p> : null}{!roleLoading && roleError ? <p className="mb-4 text-xs text-muted-foreground">{t("alertsRoleUnavailable")}</p> : null}
    {!session ? <SectionCard title={t("alertsPageTitle")} description={t("alertsAuthRequired")}><p className="text-sm text-muted-foreground">{t("alertsSignedOut")}</p></SectionCard> : query.isLoading ? <SectionCard title={t("alertsPageTitle")} description={t("alertsLoadingTitle")}><p className="text-sm text-muted-foreground">{t("alertsLoading")}</p></SectionCard> : query.error ? <SectionCard title={t("alertsPageTitle")} description={t("alertsErrorTitle")}><p className="text-sm text-destructive">{t("alertsLoadFailed")}</p></SectionCard> : <Tabs defaultValue="overview" className="space-y-4"><TabsList className="w-full justify-start overflow-x-auto"><TabsTrigger value="overview">{t("alertsTabOverview")}</TabsTrigger><TabsTrigger value="chats">{t("alertsTabChats")}</TabsTrigger><TabsTrigger value="routes">{t("alertsTabRoutes")}</TabsTrigger><TabsTrigger value="outbox">{t("alertsTabQueue")}</TabsTrigger><TabsTrigger value="action-requests">{t("alertsTabConfirmations")}</TabsTrigger><TabsTrigger value="alerts">{t("alertsTabAlerts")}</TabsTrigger><TabsTrigger value="health">{t("alertsTabHealth")}</TabsTrigger></TabsList>
      <TabsContent value="overview"><OverviewCards t={t} data={query.data} chats={chats} routes={routes} outbox={outbox} requests={requests} alerts={alerts} /></TabsContent>
      <TabsContent value="chats"><SectionCard title={t("alertsChatsTitle")} description={t("alertsChatsDescription")}><KnownColumnsTable rows={chats} columns={["chat_title", "chat_name", "title", "name", "chat_type", "type", "status", "created_at", "updated_at"]} emptyTitle={t("alertsChatsEmptyTitle")} emptyDescription={t("alertsChatsEmptyDescription")} t={t} lang={lang} /><UnavailableHint data={query.data?.telegramChats} t={t} /></SectionCard></TabsContent>
      <TabsContent value="routes"><SectionCard title={t("alertsRoutesTitle")} description={t("alertsRoutesDescription")}><KnownColumnsTable rows={routes} columns={["route_name", "route_type", "route", "event_type", "enabled", "status"]} primaryColumn="route_name" emptyTitle={t("alertsRoutesEmptyTitle")} emptyDescription={t("alertsRoutesEmptyDescription")} t={t} lang={lang} /><UnavailableHint data={query.data?.telegramRoutes} t={t} /></SectionCard></TabsContent>
      <TabsContent value="outbox"><SectionCard title={t("alertsQueueTitle")} description={t("alertsQueueDescription")}><KnownColumnsTable rows={outbox} columns={["message_type", "status", "destination_chat", "created_at", "error", "error_message"]} emptyTitle={t("alertsQueueEmptyTitle")} emptyDescription={t("alertsQueueEmptyDescription")} t={t} lang={lang} />{queuedOutboxRows.length > 0 ? <div className="mt-4 flex flex-wrap gap-2"><Button type="button" disabled={!session || !canManage || pendingAction !== ""} onClick={() => { void runDispatchQueue(); }}>{pendingAction === "dispatch-outbox" ? t("alertsSendingQueue") : t("alertsSendQueue")}</Button></div> : null}{failedOutboxRows.length > 0 ? <div className="mt-2"><Button type="button" variant="outline" disabled={!session || !canManage || !getOutboxMessageId(failedOutboxRows[0]) || pendingAction !== ""} onClick={() => { const outboxId = getOutboxMessageId(failedOutboxRows[0]); if (!outboxId) return fail("Missing outbox_message_id on the selected failed row."); void runAction("retry-outbox", () => supabase.functions.invoke("telegram-outbox-retry", { body: { workspace_id: WORKSPACE_ID, outbox_message_id: outboxId } })); }}>{pendingAction === "retry-outbox" ? t("alertsRetrying") : t("alertsRetrySend")}</Button></div> : null}<UnavailableHint data={query.data?.outboxPending} t={t} /></SectionCard></TabsContent>
      <TabsContent value="action-requests"><SectionCard title={t("alertsConfirmationsTitle")} description={t("alertsConfirmationsDescription")}><KnownColumnsTable rows={requests} columns={["action_type", "status", "requested_by", "requested_by_user", "created_at", "related_object", "object_type"]} emptyTitle={t("alertsConfirmationsEmptyTitle")} emptyDescription={t("alertsConfirmationsEmptyDescription")} t={t} lang={lang} />{firstActionRequest ? <div className="mt-4"><Button type="button" disabled={!session || pendingAction === "open-action-request"} onClick={() => { setSelectedActionRequest(firstActionRequest); setStatusMessage(t("alertsActionRequestOpened")); toast({ title: t("alertsOpenedTitle"), description: t("alertsActionRequestOpened") }); }}>{pendingAction === "open-action-request" ? t("alertsOpening") : t("alertsOpenActionRequest")}</Button></div> : null}{selectedActionRequest ? <div className="mt-3 rounded border border-border/60 bg-background p-3"><p className="mb-2 text-xs font-medium text-muted-foreground">{t("alertsSelectedRequestDetails")}</p><GenericDataTable rows={[selectedActionRequest]} columns={Object.keys(selectedActionRequest)} t={t} lang={lang} /></div> : null}<UnavailableHint data={query.data?.actionRequestsPending} t={t} /></SectionCard></TabsContent>
      <TabsContent value="alerts"><SectionCard title={t("alertsOperationalTitle")} description={t("alertsOperationalDescription")}><KnownColumnsTable rows={openAlerts} columns={["severity", "status", "title", "created_at", "resolved_at"]} emptyTitle={t("alertsOperationalEmptyTitle")} emptyDescription={t("alertsOperationalEmptyDescription")} t={t} lang={lang} />{firstOpenAlert ? <div className="mt-4"><Button type="button" disabled={!session || !canManage || !getAlertId(firstOpenAlert) || pendingAction === "resolve-alert"} onClick={() => { const alertId = getAlertId(firstOpenAlert); if (!alertId) return fail("Missing alert_id on the selected row."); void runAction("resolve-alert", () => supabase.functions.invoke("operational-alert-resolve", { body: { workspace_id: WORKSPACE_ID, alert_id: alertId } })); }}>{pendingAction === "resolve-alert" ? t("alertsResolving") : t("alertsCloseAlert")}</Button></div> : null}{resolvedAlerts.length > 0 ? <TechnicalDetails title={t("alertsRecentHistoryTitle")}><GenericTable rows={resolvedAlerts} emptyText={t("alertsNoRecords")} t={t} lang={lang} /></TechnicalDetails> : null}<UnavailableHint data={query.data?.operationalAlertsRecent} t={t} /></SectionCard></TabsContent>
      <TabsContent value="health"><SectionCard title={t("alertsHealthTitle")} description={t("alertsHealthDescription")}><div className="grid gap-3 md:grid-cols-3"><HealthCard label={t("alertsHealthTelegram")} value={chats.length ? t("alertsValueHealthy") : t("alertsTelegramNotConnected")} /><HealthCard label={t("alertsHealthActiveChats")} value={String(chats.length)} /><HealthCard label={t("alertsHealthRoutes")} value={String(routes.length)} /><HealthCard label={t("alertsHealthQueuedMessages")} value={String(queuedOutboxRows.length)} /><HealthCard label={t("alertsHealthErrors24h")} value={String(metricFromRows(query.data?.telegramHitlProductionHealth.rows ?? [], ["errors_24h", "telegram_errors_24h", "failed_messages_24h"]) ?? 0)} /><HealthCard label={t("alertsHealthConfirmationRequests")} value={String(requests.length)} /></div><TechnicalDetails title={t("alertsTelegramHitlTechnical")}><GenericTable rows={query.data?.telegramHitlHealth.rows ?? []} emptyText={t("alertsNoRecords")} t={t} lang={lang} /></TechnicalDetails><TechnicalDetails title={t("alertsProductionHealthTechnical")}><GenericTable rows={query.data?.telegramHitlProductionHealth.rows ?? []} emptyText={t("alertsNoRecords")} t={t} lang={lang} /></TechnicalDetails><TechnicalDetails title={t("alertsOperationalTechnical")}><GenericTable rows={query.data?.operationalAlertsHealth.rows ?? []} emptyText={t("alertsNoRecords")} t={t} lang={lang} /></TechnicalDetails></SectionCard></TabsContent>
    </Tabs>}
  </DashboardLayout>;
}

function OverviewCards({ t, data, chats, routes, outbox, requests, alerts }: { t: Translate; data: AlertsData | undefined; chats: Row[]; routes: Row[]; outbox: Row[]; requests: Row[]; alerts: Row[] }) { const cards: [TranslationKey, TranslationKey, string][] = [["alertsOverviewChatsTitle", "alertsOverviewChatsDescription", String(chats.length)], ["alertsOverviewRoutesTitle", "alertsOverviewRoutesDescription", String(routes.length)], ["alertsOverviewQueueTitle", "alertsOverviewQueueDescription", String(outbox.length)], ["alertsOverviewConfirmationsTitle", "alertsOverviewConfirmationsDescription", String(requests.length)], ["alertsOverviewOperationalTitle", "alertsOverviewOperationalDescription", String(alerts.length)], ["alertsOverviewTelegramStatusTitle", chats.length ? "alertsOverviewTelegramStatusHealthy" : "alertsTelegramNotConnected", chats.length ? t("alertsValueHealthy") : t("alertsValueWarning")]]; return <SectionCard title={t("alertsTabOverview")} description={t("alertsOverviewDescription")}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{cards.map(([title, description, value]) => <div key={title} className="rounded-lg border border-border/70 bg-card p-4"><p className="text-sm font-medium">{t(title)}</p><p className="mt-1 text-2xl font-semibold">{value}</p><p className="mt-2 text-xs text-muted-foreground">{t(description)}</p></div>)}</div><UnavailableHint data={data?.telegramChats} t={t} /></SectionCard>; }
function HealthCard({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-border/70 bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>; }
function TechnicalDetails({ title, children }: { title: string; children: ReactNode }) { return <details className="mt-4 rounded-md border border-border/70 bg-muted/20 p-3"><summary className="cursor-pointer text-sm font-medium text-muted-foreground">{title}</summary><div className="mt-3 text-xs text-muted-foreground">{children}</div></details>; }

type DispatchResult = { ok?: boolean; error?: string; details?: string; sent_count?: number; failed_count?: number; messages_seen?: number };
type FunctionInvokeError = { message: string; context?: unknown };
const isOutboxStatus = (row: Row, status: string) => String(row.status ?? "").toLowerCase() === status;
const hasDispatchCounts = (result: DispatchResult) => typeof result.sent_count === "number" || typeof result.failed_count === "number";
function formatDispatchResult(result: DispatchResult | null, t: Translate) { if (!result) return t("alertsQueueProcessed"); if (hasDispatchCounts(result)) return `${t("alertsQueueProcessed")} ${t("alertsSentCount")}: ${result.sent_count ?? 0}, ${t("alertsFailedCount")}: ${result.failed_count ?? 0}.`; if (result.error || result.details) return t("alertsQueueFailedDescription"); return t("alertsQueueProcessed"); }
async function getFunctionErrorMessage(error: FunctionInvokeError) { const details = await readFunctionErrorDetails(error.context); return details ? `${error.message}: ${details}` : error.message; }
async function readFunctionErrorDetails(context: unknown) { if (!(context instanceof Response)) return ""; try { const payload = await context.clone().json() as { error?: unknown; details?: unknown; message?: unknown; reason?: unknown }; return [payload.error, payload.details, payload.message, payload.reason].filter((value) => value !== undefined && value !== null && value !== "").map(String).join(" "); } catch { try { return await context.clone().text(); } catch { return ""; } } }
const getOutboxMessageId = (row: Row | undefined) => String(row?.outbox_message_id ?? row?.id ?? row?.message_id ?? "");
const getAlertId = (row: Row | undefined) => String(row?.alert_id ?? row?.id ?? "");
function isResolvedAlert(row: Row) { return String(row.status ?? "").toLowerCase() === "resolved" || Boolean(row.resolved_at); }
function isPlaceholderRow(row: Row) { const text = Object.values(row).join(" ").toLowerCase(); return PLACEHOLDER_PATTERNS.some((p) => text.includes(p)); }
function filterRows(rows: Row[]) { return rows.filter((r) => !isPlaceholderRow(r)); }
async function readOptionalView(viewName: string): Promise<OptionalViewData> { const result = await supabase.from(viewName).select("*"); if (result.error) return { rows: [], unavailableReason: result.error.message }; return { rows: (result.data ?? []) as Row[], unavailableReason: null }; }
function UnavailableHint({ data, t }: { data: OptionalViewData | undefined; t: Translate }) { if (!data?.unavailableReason) return null; return <p className="mt-2 text-xs text-muted-foreground">{t("alertsSectionUnavailable")}</p>; }
function KnownColumnsTable({ rows, columns, emptyTitle, emptyDescription, t, lang, primaryColumn }: { rows: Row[]; columns: string[]; emptyTitle: string; emptyDescription: string; t: Translate; lang: Lang; primaryColumn?: string }) { const availableColumns = columns.filter((column) => rows.some((row) => row[column] !== undefined)); if (rows.length === 0) return <div className="rounded-md border border-dashed border-border/70 bg-muted/20 p-4"><p className="text-sm font-medium">{emptyTitle}</p><p className="mt-1 text-sm text-muted-foreground">{emptyDescription}</p></div>; if (availableColumns.length === 0) return <GenericTable rows={rows} emptyText={emptyTitle} t={t} lang={lang} />; return <GenericDataTable rows={rows} columns={availableColumns} t={t} lang={lang} primaryColumn={primaryColumn} />; }
function GenericTable({ rows, emptyText, t, lang }: { rows: Row[]; emptyText: string; t: Translate; lang: Lang }) { if (rows.length === 0) return <p className="text-sm text-muted-foreground">{emptyText}</p>; const columns = Object.keys(rows[0] ?? {}); if (columns.length === 0) return <p className="text-sm text-muted-foreground">{t("alertsNoDisplayFields")}</p>; return <GenericDataTable rows={rows} columns={columns} t={t} lang={lang} />; }
function GenericDataTable({ rows, columns, t, lang, primaryColumn }: { rows: Row[]; columns: string[]; t: Translate; lang: Lang; primaryColumn?: string }) { return <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-border/70 text-muted-foreground">{columns.map((column) => <th key={column} className="px-2 py-2 font-medium">{friendlyLabel(column, t)}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${index}-${row.id ?? "row"}`} className="border-b border-border/40 last:border-0">{columns.map((column) => <td key={`${index}-${column}`} className="px-2 py-2 text-foreground">{formatValue(row[column], column, t, lang, primaryColumn ? row : undefined)}</td>)}</tr>)}</tbody></table></div>; }
function friendlyLabel(value: string, t: Translate) { if (value === "Workspace ID") return value; const normalized = value.toLowerCase().replace(/\s+/g, "_"); return COLUMN_LABEL_KEYS[normalized] ? t(COLUMN_LABEL_KEYS[normalized]) : value.split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); }
function formatValue(value: string | number | boolean | null | undefined, column: string, t: Translate, lang: Lang, row?: Row) { if (value === null || value === undefined || value === "") return "—"; const text = String(value); if (column.endsWith("_at") || column.includes("date")) return formatDateTime(text, lang); if (column === "route_name") return formatRouteName(row, text, t); if (column === "event_type") return <span>{EVENT_LABEL_KEYS[text] ? t(EVENT_LABEL_KEYS[text]) : text}<span className="block text-xs text-muted-foreground">{text}</span></span>; return VALUE_LABEL_KEYS[text.toLowerCase()] ? t(VALUE_LABEL_KEYS[text.toLowerCase()]) : text; }
function formatRouteName(row: Row | undefined, fallback: string, t: Translate) { const eventType = String(row?.event_type ?? row?.route_name ?? row?.route ?? fallback); const labelKey = EVENT_LABEL_KEYS[eventType]; if (!labelKey) return fallback; return <span>{t(labelKey)}<span className="block text-xs text-muted-foreground">{fallback}</span></span>; }
function formatDateTime(value: string, lang: Lang) { const date = new Date(value); if (Number.isNaN(date.getTime())) return value; return new Intl.DateTimeFormat(lang === "uk" ? "uk-UA" : "en-US", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Kyiv" }).format(date); }
function metricFromRows(rows: Row[], keys: string[]) { for (const row of rows) for (const key of keys) { const value = row[key]; if (typeof value === "number") return value; if (typeof value === "string" && value.trim() !== "" && !Number.isNaN(Number(value))) return Number(value); } return null; }
