import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { SectionCard } from "@/components/dashboard/SectionCard";
import { useAuth } from "@/auth/AuthProvider";
import { supabase } from "@/integrations/supabase/client";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { DeveloperDetails, FriendlyError } from "@/components/common/DeveloperDetails";
import { useWorkspaceRole } from "@/hooks/useWorkspaceRole";

const WORKSPACE_ID = "5ebbe435-fd79-44c3-834e-642e8fba00dc";
type Row = Record<string, string | number | boolean | null>;
type OptionalViewData = { rows: Row[]; unavailableReason: string | null };
type BindingsData = { sourceBindings: Row[]; adAccountBindings: Row[]; projectDataBindings: Row[]; mappingReviewQueue: Row[]; bindingHealth: Row[]; mappingReviewHealth: OptionalViewData; mappingReviewActionsRecent: OptionalViewData; telegramHitlHealth: OptionalViewData; };
type BindingType = "source" | "ad_account";

export default function Bindings() {
  const { session } = useAuth();
  const queryClient = useQueryClient();
  const { capabilities, isLoading: roleLoading, error: roleError } = useWorkspaceRole(WORKSPACE_ID);
  const canManage = capabilities.can_manage_bindings || capabilities.can_manage_mapping_review;
  const [message, setMessage] = useState<string>("Дії перевіряються перед виконанням.");
  const [pending, setPending] = useState<string>("");
  const [sourceForm, setSourceForm] = useState({ source_id: "", client_id: "", project_id: "", funnel_id: "" });
  const [adForm, setAdForm] = useState({ ad_account_id: "", client_id: "", project_id: "", funnel_id: "" });
  const query = useQuery<BindingsData>({ queryKey: ["bindings-mapping-workspace", WORKSPACE_ID], enabled: Boolean(session), queryFn: async () => {
    const [sourceRes, adRes, projectRes, queueRes, healthRes] = await Promise.all([supabase.from("v_source_entity_bindings").select("*"), supabase.from("v_ad_account_bindings").select("*"), supabase.from("v_project_data_bindings").select("*"), supabase.from("v_mapping_review_queue").select("*"), supabase.from("v_binding_health").select("*")]);
    if (sourceRes.error) throw sourceRes.error; if (adRes.error) throw adRes.error; if (projectRes.error) throw projectRes.error; if (queueRes.error) throw queueRes.error; if (healthRes.error) throw healthRes.error;
    const [mappingReviewHealth, mappingReviewActionsRecent, telegramHitlHealth] = await Promise.all([readOptionalView("v_mapping_review_health"), readOptionalView("v_mapping_review_actions_recent"), readOptionalView("v_telegram_hitl_production_health")]);
    return { sourceBindings: (sourceRes.data ?? []) as Row[], adAccountBindings: (adRes.data ?? []) as Row[], projectDataBindings: (projectRes.data ?? []) as Row[], mappingReviewQueue: (queueRes.data ?? []) as Row[], bindingHealth: (healthRes.data ?? []) as Row[], mappingReviewHealth, mappingReviewActionsRecent, telegramHitlHealth };
  }});

  const runAction = async (key: string, fn: () => Promise<{ data: unknown; error: { message: string } | null }>) => {
    setPending(key); setMessage("");
    const { data, error } = await fn();
    setPending("");
    if (error) { setMessage("Цей розділ поки недоступний."); return; }
    if ((data as { ok?: boolean; error?: string } | null)?.ok === false) { setMessage((data as { error?: string }).error ?? "Action failed"); return; }
    setMessage("Action completed successfully.");
    await query.refetch();
    await Promise.all(["v_source_entity_bindings","v_ad_account_bindings","v_project_data_bindings","v_mapping_review_queue","v_binding_health","v_mapping_review_health","v_mapping_review_actions_recent"].map((qk) => queryClient.invalidateQueries({ queryKey: [qk, WORKSPACE_ID] })));
  };

  const queueRows = useMemo(() => query.data?.mappingReviewQueue ?? [], [query.data?.mappingReviewQueue]);
  const firstQueue = queueRows[0];

  return <DashboardLayout title="Звʼязки даних" subtitle="Керування звʼязками даних">{!session ? <SectionCard title="Bindings / Mapping" description="Authentication required"><p className="text-sm text-muted-foreground">You are signed out. Sign in to access bindings and mapping review data.</p></SectionCard> : query.isLoading ? <SectionCard title="Bindings / Mapping" description="Loading data"><p className="text-sm text-muted-foreground">Loading bindings workspace…</p></SectionCard> : query.error ? <SectionCard title="Bindings / Mapping" description="Стан розділу"><FriendlyError message="Потрібне оновлення backend для цього розділу." technical={query.error.message} /></SectionCard> : <Tabs defaultValue="overview" className="space-y-4"><TabsList className="w-full justify-start overflow-x-auto"><TabsTrigger value="overview">Огляд</TabsTrigger><TabsTrigger value="source">Джерела даних</TabsTrigger><TabsTrigger value="ad-account">Рекламні акаунти</TabsTrigger><TabsTrigger value="project-data">Звʼязки з проєктами</TabsTrigger><TabsTrigger value="mapping-review">Мапінг на перевірку</TabsTrigger><TabsTrigger value="health">Стан підключень</TabsTrigger></TabsList>
    <p className="text-xs text-muted-foreground">{message}</p>{roleLoading ? <p className="text-xs text-muted-foreground">Перевіряємо доступ…</p> : null}{!roleLoading && !canManage ? <p className="text-xs text-muted-foreground">У вас немає доступу до керування цим розділом.</p> : null}{!roleLoading && roleError ? <p className="text-xs text-muted-foreground">Доступ тимчасово не підтягнувся. Дії вимкнені.</p> : null}
    <TabsContent value="overview"><SectionCard title="Огляд звʼязків" description="Короткий стан підключень"><ul className="grid gap-2 text-sm md:grid-cols-2"><li>Джерела даних: <strong>{query.data?.sourceBindings.length ?? 0}</strong></li><li>Рекламні акаунти: <strong>{query.data?.adAccountBindings.length ?? 0}</strong></li><li>Звʼязки з проєктами: <strong>{query.data?.projectDataBindings.length ?? 0}</strong></li><li>Мапінг на перевірку: <strong>{query.data?.mappingReviewQueue.length ?? 0}</strong></li></ul></SectionCard></TabsContent>
    <TabsContent value="source"><SectionCard title="Джерела даних" description="Підключені джерела даних"><details className="mb-3 rounded-md border border-border/70 bg-muted/20 p-3"><summary className="cursor-pointer font-medium">Розширене налаштування</summary><p className="mt-2 text-xs text-muted-foreground">Цей блок для адміністратора. Використовуйте його тільки якщо маєте точні ID.</p><div className="mt-2 flex flex-wrap gap-2"><input className="rounded border px-2 py-1 text-sm" placeholder="source_id" value={sourceForm.source_id} onChange={(e) => setSourceForm((s) => ({ ...s, source_id: e.target.value }))} /><input className="rounded border px-2 py-1 text-sm" placeholder="client_id" value={sourceForm.client_id} onChange={(e) => setSourceForm((s) => ({ ...s, client_id: e.target.value }))} /><input className="rounded border px-2 py-1 text-sm" placeholder="project_id" value={sourceForm.project_id} onChange={(e) => setSourceForm((s) => ({ ...s, project_id: e.target.value }))} /><input className="rounded border px-2 py-1 text-sm" placeholder="funnel_id" value={sourceForm.funnel_id} onChange={(e) => setSourceForm((s) => ({ ...s, funnel_id: e.target.value }))} /><Button disabled={!session || !canManage || !sourceForm.source_id || pending === "create-source"} onClick={() => runAction("create-source", () => supabase.functions.invoke("binding-create-or-update", { body: { workspace_id: WORKSPACE_ID, binding_type: "source", ...sourceForm } }))}>{pending === "create-source" ? "Зберігаємо..." : "Зберегти звʼязок джерела"}</Button></div></details><KnownColumnsTable rows={query.data?.sourceBindings ?? []} columns={["source_name","source_kind","platform","client_name","project_name","funnel_name","mapping_status","binding_status","confidence","binding_method","created_at","updated_at"]} emptyText="Джерела даних ще не привʼязані." /></SectionCard></TabsContent>
    <TabsContent value="ad-account"><SectionCard title="Рекламні акаунти" description="Підключені рекламні акаунти"><details className="mb-3 rounded-md border border-border/70 bg-muted/20 p-3"><summary className="cursor-pointer font-medium">Розширене налаштування</summary><p className="mt-2 text-xs text-muted-foreground">Цей блок для адміністратора. Використовуйте його тільки якщо маєте точні ID.</p><div className="mt-2 flex flex-wrap gap-2"><input className="rounded border px-2 py-1 text-sm" placeholder="ad_account_id" value={adForm.ad_account_id} onChange={(e) => setAdForm((s) => ({ ...s, ad_account_id: e.target.value }))} /><input className="rounded border px-2 py-1 text-sm" placeholder="client_id" value={adForm.client_id} onChange={(e) => setAdForm((s) => ({ ...s, client_id: e.target.value }))} /><input className="rounded border px-2 py-1 text-sm" placeholder="project_id" value={adForm.project_id} onChange={(e) => setAdForm((s) => ({ ...s, project_id: e.target.value }))} /><input className="rounded border px-2 py-1 text-sm" placeholder="funnel_id" value={adForm.funnel_id} onChange={(e) => setAdForm((s) => ({ ...s, funnel_id: e.target.value }))} /><Button disabled={!session || !canManage || !adForm.ad_account_id || pending === "create-ad"} onClick={() => runAction("create-ad", () => supabase.functions.invoke("binding-create-or-update", { body: { workspace_id: WORKSPACE_ID, binding_type: "ad_account", ...adForm } }))}>{pending === "create-ad" ? "Зберігаємо..." : "Зберегти звʼязок рекламного акаунта"}</Button></div></details><KnownColumnsTable rows={query.data?.adAccountBindings ?? []} columns={["ad_account_name","external_account_id","platform","client_name","project_name","funnel_name","mapping_status","binding_status","confidence","binding_method","created_at","updated_at"]} emptyText="Рекламні акаунти ще не привʼязані." /></SectionCard></TabsContent>
    <TabsContent value="project-data"><SectionCard title="Звʼязки з проєктами" description="Звʼязки даних із проєктами"><KnownColumnsTable rows={query.data?.projectDataBindings ?? []} columns={["client_name","project_name","funnel_name","source_name","ad_account_name","platform","source_kind","binding_type","mapping_status","health_status","binding_status"]} emptyText="Звʼязків із проєктами поки немає." /></SectionCard></TabsContent>
    <TabsContent value="mapping-review"><SectionCard title="Мапінг на перевірку" description="Звʼязки, які потрібно перевірити"><KnownColumnsTable rows={query.data?.mappingReviewQueue ?? []} columns={["source_name","ad_account_name","proposed_client_name","proposed_project_name","proposed_funnel_name","confidence","mapping_status","binding_method","reason","details","created_at"]} emptyText="Немає мапінгу на перевірку." /><div className="mt-4 rounded-md border border-dashed border-border/70 bg-muted/30 p-3"><div className="flex flex-wrap gap-2"><Button type="button" disabled={!session || !canManage || !firstQueue || pending === "send-telegram"} onClick={() => runAction("send-telegram", () => supabase.functions.invoke("mapping-review-send-telegram", { body: { workspace_id: WORKSPACE_ID, binding_type: getBindingType(firstQueue), binding_id: getBindingId(firstQueue) } }))}>{pending === "send-telegram" ? "Виконуємо..." : "Надіслати в Telegram на підтвердження"}</Button><Button type="button" variant="outline" disabled={!session || !canManage || !firstQueue || pending === "approve"} onClick={() => runAction("approve", () => supabase.functions.invoke("mapping-review-approve", { body: { workspace_id: WORKSPACE_ID, binding_type: getBindingType(firstQueue), binding_id: getBindingId(firstQueue) } }))}>{pending === "approve" ? "Виконуємо..." : "Підтвердити"}</Button><Button type="button" variant="destructive" disabled={!session || !canManage || !firstQueue || pending === "reject"} onClick={() => runAction("reject", () => supabase.functions.invoke("mapping-review-reject", { body: { workspace_id: WORKSPACE_ID, binding_type: getBindingType(firstQueue), binding_id: getBindingId(firstQueue) } }))}>{pending === "reject" ? "Виконуємо..." : "Відхилити"}</Button></div></div></SectionCard></TabsContent>
    <TabsContent value="health"><div className="space-y-4"><SectionCard title="Стан підключень" description="Стан підключень"><GenericTable rows={query.data?.bindingHealth ?? []} emptyText="Даних про стан підключень поки немає." /></SectionCard><OptionalViewCard title="Стан перевірки мапінгу" viewName="v_mapping_review_health" data={query.data?.mappingReviewHealth} /><OptionalViewCard title="Останні дії з мапінгом" viewName="v_mapping_review_actions_recent" data={query.data?.mappingReviewActionsRecent} /><OptionalViewCard title="Стан Telegram-підтверджень" viewName="v_telegram_hitl_production_health" data={query.data?.telegramHitlHealth} /></div></TabsContent>
    </Tabs>}</DashboardLayout>;
}
const getBindingId = (row: Row) => String(row.binding_id ?? row.id ?? "");
const getBindingType = (row: Row): BindingType => String(row.binding_type ?? "source") === "ad_account" ? "ad_account" : "source";
async function readOptionalView(viewName: string): Promise<OptionalViewData> { const result = await supabase.from(viewName).select("*"); if (result.error) return { rows: [], unavailableReason: result.error.message }; return { rows: (result.data ?? []) as Row[], unavailableReason: null }; }
function OptionalViewCard({ title, viewName, data }: { title: string; viewName: string; data: OptionalViewData | undefined }) { return <SectionCard title={title} description="Деталі">{data?.unavailableReason ? <p className="text-sm text-muted-foreground">Цей розділ поки недоступний.</p> : <GenericTable rows={data?.rows ?? []} emptyText="Записів поки немає." />}<DeveloperDetails><p>{viewName}</p>{data?.unavailableReason ? <p>{data.unavailableReason}</p> : null}</DeveloperDetails></SectionCard>; }
function KnownColumnsTable({ rows, columns, emptyText }: { rows: Row[]; columns: string[]; emptyText: string }) { const availableColumns = columns.filter((column) => rows.some((row) => row[column] !== undefined)); if (rows.length === 0) return <p className="text-sm text-muted-foreground">{emptyText}</p>; if (availableColumns.length === 0) return <GenericTable rows={rows} emptyText={emptyText} />; return <GenericDataTable rows={rows} columns={availableColumns} />; }
function GenericTable({ rows, emptyText }: { rows: Row[]; emptyText: string }) { if (rows.length === 0) return <p className="text-sm text-muted-foreground">{emptyText}</p>; const columns = Object.keys(rows[0] ?? {}); if (columns.length === 0) return <p className="text-sm text-muted-foreground">Data exists but has no displayable fields.</p>; return <GenericDataTable rows={rows} columns={columns} />; }
function GenericDataTable({ rows, columns }: { rows: Row[]; columns: string[] }) { return <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-border/70 text-muted-foreground">{columns.map((column) => <th key={column} className="px-2 py-2 font-medium">{titleize(column)}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${index}-${row.id ?? "row"}`} className="border-b border-border/40 last:border-0">{columns.map((column) => <td key={`${index}-${column}`} className="px-2 py-2 text-foreground">{formatValue(row[column])}</td>)}</tr>)}</tbody></table></div>; }
function titleize(value: string) { return value.split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); }
function formatValue(value: string | number | boolean | null | undefined) { return value === null || value === undefined || value === "" ? "—" : String(value); }
